helloworld_bot:
    path: /helloworld-bot
    controller: Talkspirit\BotDemo\Controller\AppController::helloWorldBot
    methods:    [POST]

google_bot:
    path: /google-bot
    controller: Talkspirit\BotDemo\Controller\AppController::googleBot
    methods:    [POST]

health_check:
    path: /
    controller: Talkspirit\BotDemo\Controller\AppController::healthCheck
    methods:    [GET, HEAD]
