app:
    path: /
    controller: BotDemo\Controller\AppController::index
    methods:    [POST]

health_check:
    path: /
    controller: BotDemo\Controller\AppController::healthCheck
    methods:    [GET, HEAD]
